seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: /home/stormer/results/finetune/

  precision: 16

  devices: 1
  num_nodes: 1
  accelerator: gpu
  strategy: ddp

  min_epochs: 1
  max_epochs: 20
  enable_progress_bar: true

  sync_batchnorm: True
  enable_checkpointing: True
  num_sanity_val_steps: 1

  # debugging
  fast_dev_run: false

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: 'stormer'
      save_dir: ${trainer.default_root_dir}/finetune_4_steps
      name: finetune_4_steps

  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/finetune_4_steps/checkpoints"
        monitor: "val/w_mse_aggregate_168_hrs_ensemble_mean" # name of the logged metric which determines when model is improving
        mode: "min"
        save_top_k: 1 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: False
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False

    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: lightning.pytorch.callbacks.TQDMProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 5e-6
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_epochs: 2
  max_epochs: 20
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  weighted_loss: True
  pretrained_path: null # should be specified

  net:
    class_path: stormer.models.hub.stormer.Stormer
    init_args:
      list_variables: [
        "2m_temperature",
        "10m_u_component_of_wind",
        "10m_v_component_of_wind",
        "mean_sea_level_pressure",
        "geopotential_50",
        "geopotential_100",
        "geopotential_150",
        "geopotential_200",
        "geopotential_250",
        "geopotential_300",
        "geopotential_400",
        "geopotential_500",
        "geopotential_600",
        "geopotential_700",
        "geopotential_850",
        "geopotential_925",
        "geopotential_1000",
        "u_component_of_wind_50",
        "u_component_of_wind_100",
        "u_component_of_wind_150",
        "u_component_of_wind_200",
        "u_component_of_wind_250",
        "u_component_of_wind_300",
        "u_component_of_wind_400",
        "u_component_of_wind_500",
        "u_component_of_wind_600",
        "u_component_of_wind_700",
        "u_component_of_wind_850",
        "u_component_of_wind_925",
        "u_component_of_wind_1000",
        "v_component_of_wind_50",
        "v_component_of_wind_100",
        "v_component_of_wind_150",
        "v_component_of_wind_200",
        "v_component_of_wind_250",
        "v_component_of_wind_300",
        "v_component_of_wind_400",
        "v_component_of_wind_500",
        "v_component_of_wind_600",
        "v_component_of_wind_700",
        "v_component_of_wind_850",
        "v_component_of_wind_925",
        "v_component_of_wind_1000",
        "temperature_50",
        "temperature_100",
        "temperature_150",
        "temperature_200",
        "temperature_250",
        "temperature_300",
        "temperature_400",
        "temperature_500",
        "temperature_600",
        "temperature_700",
        "temperature_850",
        "temperature_925",
        "temperature_1000",
        "specific_humidity_50",
        "specific_humidity_100",
        "specific_humidity_150",
        "specific_humidity_200",
        "specific_humidity_250",
        "specific_humidity_300",
        "specific_humidity_400",
        "specific_humidity_500",
        "specific_humidity_600",
        "specific_humidity_700",
        "specific_humidity_850",
        "specific_humidity_925",
        "specific_humidity_1000",
      ]
      in_img_size: [128, 256]
      patch_size: 2
      hidden_size: 1024
      depth: 24
      num_heads: 16
      mlp_ratio: 4.0

# ---------------------------- DATA -------------------------------------------
data:
  root_dir: /home/data/wb2/0.25deg_6hr_h5df/
  variables: [
    "2m_temperature",
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "mean_sea_level_pressure",
    "geopotential_50",
    "geopotential_100",
    "geopotential_150",
    "geopotential_200",
    "geopotential_250",
    "geopotential_300",
    "geopotential_400",
    "geopotential_500",
    "geopotential_600",
    "geopotential_700",
    "geopotential_850",
    "geopotential_925",
    "geopotential_1000",
    "u_component_of_wind_50",
    "u_component_of_wind_100",
    "u_component_of_wind_150",
    "u_component_of_wind_200",
    "u_component_of_wind_250",
    "u_component_of_wind_300",
    "u_component_of_wind_400",
    "u_component_of_wind_500",
    "u_component_of_wind_600",
    "u_component_of_wind_700",
    "u_component_of_wind_850",
    "u_component_of_wind_925",
    "u_component_of_wind_1000",
    "v_component_of_wind_50",
    "v_component_of_wind_100",
    "v_component_of_wind_150",
    "v_component_of_wind_200",
    "v_component_of_wind_250",
    "v_component_of_wind_300",
    "v_component_of_wind_400",
    "v_component_of_wind_500",
    "v_component_of_wind_600",
    "v_component_of_wind_700",
    "v_component_of_wind_850",
    "v_component_of_wind_925",
    "v_component_of_wind_1000",
    "temperature_50",
    "temperature_100",
    "temperature_150",
    "temperature_200",
    "temperature_250",
    "temperature_300",
    "temperature_400",
    "temperature_500",
    "temperature_600",
    "temperature_700",
    "temperature_850",
    "temperature_925",
    "temperature_1000",
    "specific_humidity_50",
    "specific_humidity_100",
    "specific_humidity_150",
    "specific_humidity_200",
    "specific_humidity_250",
    "specific_humidity_300",
    "specific_humidity_400",
    "specific_humidity_500",
    "specific_humidity_600",
    "specific_humidity_700",
    "specific_humidity_850",
    "specific_humidity_925",
    "specific_humidity_1000",
  ]
  list_train_intervals: [6, 12, 24]
  steps: 4
  val_lead_times: [6, 72, 120, 168]
  data_freq: 6
  batch_size: 1
  val_batch_size: 1
  num_workers: 2
  pin_memory: False